# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JI360gnRSTHxM2EL1dM8hizD7XlIY0m1
"""

print("Hello World!")